{
    'name' : 'Parking Management System',
    'version' : '14.0.1.0',
    'author' : 'WEHA',
    'category' : 'Generic Modules/Parking Management System',
    'depends' : ['base','hr', 'product', 'account', 'sale'],
    'init_xml' : [],
    'data' : [
        'data/ir_config_param.xml',
        'data/weha_parking_data.xml',
        'security/jakc_parking_security.xml',
        'security/ir.model.access.csv',
        'views/jakc_parking_view.xml',
        'views/jakc_parking_booth_view.xml',
        'views/jakc_parking_pricing_view.xml',
        'views/jakc_parking_transaction_view.xml',
        'views/res_partner_view.xml',
        'views/product_view.xml',
        'views/jakc_parking_sequence.xml',
        'views/jakc_parking_menu.xml',
        'views/jakc_parking_report.xml',
        'views/jakc_parking_report_view.xml',
        'wizard/wizard_report_parking_session_summary_view.xml',
        'wizard/wizard_report_parking_summary_by_date_view.xml',
        'report/report_parking_per_session_view.xml',
        'report/report_parking_by_date_view.xml',
        'report/report_parking_entry_receipt_view.xml',
        'views/templates.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}